# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres:13
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - /apps/pgdata:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command:
      - -c
      - max_connections=600
    ports:
      - 5432:5432
